"""
This type stub file was generated by pyright.
"""

from astropy import config as _config
from .core import SkyView, SkyViewClass

class Conf(_config.ConfigNamespace):
    """
    Configuration parameters for `astroquery.skyview`.
    """
    url = ...


conf = ...
__all__ = ['SkyView', 'SkyViewClass', 'Conf', 'conf']
