from ...core import PixCoord as PixCoord, RegionMeta as RegionMeta, Regions as Regions
from ...core.registry import RegionsRegistry as RegionsRegistry
from .core import FITSParserError as FITSParserError, shape_map as shape_map

def get_shape(region_row): ...
def get_column_values(region_row, colname): ...
def get_shape_params(shape, region_row, shape_columns): ...
def parse_row(region_row): ...
def parse_table(region_table): ...
