"""
This type stub file was generated by pyright.
"""

from .functional_models import *
from .mappings import *
from .physical_models import *
from .polynomial import *
from .powerlaws import *
from .projections import *
from .rotations import *
from .spline import *
from .tabular import *

"""
Creates a common namespace for all pre-defined models.
"""
CONSTRAINTS_DOC = ...
MODELS_WITH_CONSTRAINTS = ...
