"""
This type stub file was generated by pyright.
"""

from . import core, flrw, funcs, io, parameter, realizations, units, utils
from .core import *
from .flrw import *
from .funcs import *
from .parameter import *
from .realizations import available, default_cosmology
from .utils import *

""" astropy.cosmology contains classes and functions for cosmological
distance measures and other cosmology-related calculations.

See the `Astropy documentation
<https://docs.astropy.org/en/latest/cosmology/index.html>`_ for more
detailed usage examples and references.

"""
__all__ = (core.__all__ + flrw.__all__ + realizations.__all__ + ["units"] + funcs.__all__ + parameter.__all__ + utils.__all__)
def __getattr__(name): # -> Any:
    """Get realizations using lazy import from
    `PEP 562 <https://www.python.org/dev/peps/pep-0562/>`_.

    Raises
    ------
    AttributeError
        If "name" is not in :mod:`astropy.cosmology.realizations`
    """
    ...

def __dir__(): # -> list[str]:
    """Directory, including lazily-imported objects."""
    ...

