from _typeshed import Incomplete

class RegionBoundingBox:
    ixmin: Incomplete
    ixmax: Incomplete
    iymin: Incomplete
    iymax: Incomplete
    def __init__(self, ixmin, ixmax, iymin, iymax) -> None: ...
    @classmethod
    def from_float(cls, xmin, xmax, ymin, ymax): ...
    def __eq__(self, other): ...
    def __or__(self, other): ...
    def __and__(self, other): ...
    @property
    def center(self): ...
    @property
    def shape(self): ...
    def get_overlap_slices(self, shape): ...
    @property
    def extent(self): ...
    def as_artist(self, **kwargs): ...
    def to_region(self): ...
    def plot(self, origin=..., ax: Incomplete | None = ..., **kwargs): ...
    def union(self, other): ...
    def intersection(self, other): ...
