from _typeshed import Incomplete

class RegionMask:
    data: Incomplete
    bbox: Incomplete
    def __init__(self, data, bbox) -> None: ...
    def __array__(self): ...
    @property
    def shape(self): ...
    def get_overlap_slices(self, shape): ...
    def to_image(self, shape): ...
    def cutout(self, data, fill_value: float = ..., copy: bool = ...): ...
    def multiply(self, data, fill_value: float = ...): ...
    def get_values(self, data, mask: Incomplete | None = ...): ...
