from _typeshed import Incomplete

class Meta(dict):
    valid_keys: Incomplete
    key_mapping: Incomplete
    def __init__(self, seq: Incomplete | None = ..., **kwargs) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, item): ...
    def update(self, *args, **kwargs) -> None: ...
    def setdefault(self, key, value: Incomplete | None = ...): ...
    def copy(self): ...

class RegionMeta(Meta):
    valid_keys: Incomplete
    key_mapping: Incomplete

class RegionVisual(Meta):
    valid_keys: Incomplete
    key_mapping: Incomplete
    def define_mpl_kwargs(self, artist): ...
