from _typeshed import Incomplete

def make_example_dataset(data: str = ..., config: Incomplete | None = ...): ...

class ExampleDataset:
    config: Incomplete
    def __init__(self, config: Incomplete | None = ...) -> None: ...
    def wcs(self): ...
    def image(self): ...
    def hdu_list(self): ...

class ExampleDatasetSimulated(ExampleDataset):
    def source_table(self): ...
    def event_table(self): ...

class ExampleDatasetFermi(ExampleDataset):
    def source_table(self): ...
    def event_table(self): ...
