"""
This type stub file was generated by pyright.
"""

def append_docstr(doc): # -> (fn: Unknown) -> Unknown:
    """ Decorator to append to the function's docstr """
    ...

def prepend_docstr_nosections(doc, sections=...): # -> (fn: Unknown) -> Unknown:
    """
    Decorator to prepend to the function's docstr after stripping out the
    list of sections provided (by default "Returns" only).
    """
    ...

def remove_sections(doc, sections): # -> list[Unknown]:
    """
    Given a numpy-formatted docstring, remove the section blocks provided in
    ``sections`` and dedent the whole thing.

    Returns
    -------
    List of lines
    """
    ...

