"""
This type stub file was generated by pyright.
"""
import logging
from astropy.logger import AstropyLogger
def _init_log(config=None):
    """
    Initializes the logger, using the AstropyLogger class.
    """
    orig_logger_cls = logging.getLoggerClass()
    logging.setLoggerClass(AstropyLogger)
    try:
        log = logging.getLogger('astroquery')
        if config is not None:
            _config_to_loggerConf(config)
        log._set_defaults()
    finally:
        logging.setLoggerClass(orig_logger_cls)

    return log