from _typeshed import Incomplete
from matplotlib import cbook as cbook
from matplotlib.axes._axes import Axes as Axes
from matplotlib.gridspec import SubplotSpec as SubplotSpec

class SubplotBase:
    def __init__(self, fig, *args, **kwargs) -> None: ...
    def get_subplotspec(self): ...
    def set_subplotspec(self, subplotspec) -> None: ...
    def get_gridspec(self): ...
    def label_outer(self) -> None: ...

subplot_class_factory: Incomplete
Subplot: Incomplete
