from typing import Any

import numpy
a2af: numpy.ufunc
a2tf: numpy.ufunc
ab: numpy.ufunc
ae2hd: numpy.ufunc
af2a: numpy.ufunc
anp: numpy.ufunc
anpm: numpy.ufunc
apcg: numpy.ufunc
apcg13: numpy.ufunc
apci: numpy.ufunc
apci13: numpy.ufunc
apco: numpy.ufunc
apco13: numpy.ufunc
apcs: numpy.ufunc
apcs13: numpy.ufunc
aper: numpy.ufunc
aper13: numpy.ufunc
apio: numpy.ufunc
apio13: numpy.ufunc
atcc13: numpy.ufunc
atccq: numpy.ufunc
atci13: numpy.ufunc
atciq: numpy.ufunc
atciqn: numpy.ufunc
atciqz: numpy.ufunc
atco13: numpy.ufunc
atic13: numpy.ufunc
aticq: numpy.ufunc
aticqn: numpy.ufunc
atio13: numpy.ufunc
atioq: numpy.ufunc
atoc13: numpy.ufunc
atoi13: numpy.ufunc
atoiq: numpy.ufunc
bi00: numpy.ufunc
bp00: numpy.ufunc
bp06: numpy.ufunc
bpn2xy: numpy.ufunc
c2i00a: numpy.ufunc
c2i00b: numpy.ufunc
c2i06a: numpy.ufunc
c2ibpn: numpy.ufunc
c2ixy: numpy.ufunc
c2ixys: numpy.ufunc
c2s: numpy.ufunc
c2t00a: numpy.ufunc
c2t00b: numpy.ufunc
c2t06a: numpy.ufunc
c2tcio: numpy.ufunc
c2teqx: numpy.ufunc
c2tpe: numpy.ufunc
c2txy: numpy.ufunc
cal2jd: numpy.ufunc
cp: numpy.ufunc
cpv: numpy.ufunc
cr: numpy.ufunc
d2dtf: numpy.ufunc
d2tf: numpy.ufunc
dat: numpy.ufunc
dt_dmsf: numpy.dtype[void]
dt_eraASTROM: numpy.dtype[void]
dt_eraLDBODY: numpy.dtype[void]
dt_eraLEAPSECOND: numpy.dtype[void]
dt_hmsf: numpy.dtype[void]
dt_pv: numpy.dtype[void]
dt_pvdpv: numpy.dtype[void]
dt_sign: numpy.dtype[void]
dt_type: numpy.dtype[void]
dt_ymdf: numpy.dtype[void]
dtdb: numpy.ufunc
dtf2d: numpy.ufunc
eceq06: numpy.ufunc
ecm06: numpy.ufunc
ee00: numpy.ufunc
ee00a: numpy.ufunc
ee00b: numpy.ufunc
ee06a: numpy.ufunc
eect00: numpy.ufunc
eform: numpy.ufunc
eo06a: numpy.ufunc
eors: numpy.ufunc
epb: numpy.ufunc
epb2jd: numpy.ufunc
epj: numpy.ufunc
epj2jd: numpy.ufunc
epv00: numpy.ufunc
eqec06: numpy.ufunc
eqeq94: numpy.ufunc
era00: numpy.ufunc
erfa_version: str
fad03: numpy.ufunc
fae03: numpy.ufunc
faf03: numpy.ufunc
faju03: numpy.ufunc
fal03: numpy.ufunc
falp03: numpy.ufunc
fama03: numpy.ufunc
fame03: numpy.ufunc
fane03: numpy.ufunc
faom03: numpy.ufunc
fapa03: numpy.ufunc
fasa03: numpy.ufunc
faur03: numpy.ufunc
fave03: numpy.ufunc
fk425: numpy.ufunc
fk45z: numpy.ufunc
fk524: numpy.ufunc
fk52h: numpy.ufunc
fk54z: numpy.ufunc
fk5hip: numpy.ufunc
fk5hz: numpy.ufunc
fw2m: numpy.ufunc
fw2xy: numpy.ufunc
g2icrs: numpy.ufunc
gc2gd: numpy.ufunc
gc2gde: numpy.ufunc
gd2gc: numpy.ufunc
gd2gce: numpy.ufunc
gmst00: numpy.ufunc
gmst06: numpy.ufunc
gmst82: numpy.ufunc
gst00a: numpy.ufunc
gst00b: numpy.ufunc
gst06: numpy.ufunc
gst06a: numpy.ufunc
gst94: numpy.ufunc
h2fk5: numpy.ufunc
hd2ae: numpy.ufunc
hd2pa: numpy.ufunc
hfk5z: numpy.ufunc
icrs2g: numpy.ufunc
ir: numpy.ufunc
jd2cal: numpy.ufunc
jdcalf: numpy.ufunc
ld: numpy.ufunc
ldn: numpy.ufunc
ldsun: numpy.ufunc
lteceq: numpy.ufunc
ltecm: numpy.ufunc
lteqec: numpy.ufunc
ltp: numpy.ufunc
ltpb: numpy.ufunc
ltpecl: numpy.ufunc
ltpequ: numpy.ufunc
moon98: numpy.ufunc
num00a: numpy.ufunc
num00b: numpy.ufunc
num06a: numpy.ufunc
numat: numpy.ufunc
nut00a: numpy.ufunc
nut00b: numpy.ufunc
nut06a: numpy.ufunc
nut80: numpy.ufunc
nutm80: numpy.ufunc
obl06: numpy.ufunc
obl80: numpy.ufunc
p06e: numpy.ufunc
p2pv: numpy.ufunc
p2s: numpy.ufunc
pap: numpy.ufunc
pas: numpy.ufunc
pb06: numpy.ufunc
pdp: numpy.ufunc
pfw06: numpy.ufunc
plan94: numpy.ufunc
pm: numpy.ufunc
pmat00: numpy.ufunc
pmat06: numpy.ufunc
pmat76: numpy.ufunc
pmp: numpy.ufunc
pmpx: numpy.ufunc
pmsafe: numpy.ufunc
pn: numpy.ufunc
pn00: numpy.ufunc
pn00a: numpy.ufunc
pn00b: numpy.ufunc
pn06: numpy.ufunc
pn06a: numpy.ufunc
pnm00a: numpy.ufunc
pnm00b: numpy.ufunc
pnm06a: numpy.ufunc
pnm80: numpy.ufunc
pom00: numpy.ufunc
ppp: numpy.ufunc
ppsp: numpy.ufunc
pr00: numpy.ufunc
prec76: numpy.ufunc
pv2p: numpy.ufunc
pv2s: numpy.ufunc
pvdpv: numpy.ufunc
pvm: numpy.ufunc
pvmpv: numpy.ufunc
pvppv: numpy.ufunc
pvstar: numpy.ufunc
pvtob: numpy.ufunc
pvu: numpy.ufunc
pvup: numpy.ufunc
pvxpv: numpy.ufunc
pxp: numpy.ufunc
refco: numpy.ufunc
rm2v: numpy.ufunc
rv2m: numpy.ufunc
rx: numpy.ufunc
rxp: numpy.ufunc
rxpv: numpy.ufunc
rxr: numpy.ufunc
ry: numpy.ufunc
rz: numpy.ufunc
s00: numpy.ufunc
s00a: numpy.ufunc
s00b: numpy.ufunc
s06: numpy.ufunc
s06a: numpy.ufunc
s2c: numpy.ufunc
s2p: numpy.ufunc
s2pv: numpy.ufunc
s2xpv: numpy.ufunc
sepp: numpy.ufunc
seps: numpy.ufunc
sofa_version: str
sp00: numpy.ufunc
starpm: numpy.ufunc
starpv: numpy.ufunc
sxp: numpy.ufunc
sxpv: numpy.ufunc
taitt: numpy.ufunc
taiut1: numpy.ufunc
taiutc: numpy.ufunc
tcbtdb: numpy.ufunc
tcgtt: numpy.ufunc
tdbtcb: numpy.ufunc
tdbtt: numpy.ufunc
tf2a: numpy.ufunc
tf2d: numpy.ufunc
tpors: numpy.ufunc
tporv: numpy.ufunc
tpsts: numpy.ufunc
tpstv: numpy.ufunc
tpxes: numpy.ufunc
tpxev: numpy.ufunc
tr: numpy.ufunc
trxp: numpy.ufunc
trxpv: numpy.ufunc
tttai: numpy.ufunc
tttcg: numpy.ufunc
tttdb: numpy.ufunc
ttut1: numpy.ufunc
ut1tai: numpy.ufunc
ut1tt: numpy.ufunc
ut1utc: numpy.ufunc
utctai: numpy.ufunc
utcut1: numpy.ufunc
xy06: numpy.ufunc
xys00a: numpy.ufunc
xys00b: numpy.ufunc
xys06a: numpy.ufunc
zp: numpy.ufunc
zpv: numpy.ufunc
zr: numpy.ufunc

def get_leap_seconds() -> Any: ...
def set_leap_seconds(*args, **kwargs) -> Any: ...
