from ..core.core import PixelRegion, SkyRegion
from _typeshed import Incomplete

class LinePixelRegion(PixelRegion):
    start: Incomplete
    end: Incomplete
    meta: Incomplete
    visual: Incomplete
    def __init__(self, start, end, meta: Incomplete | None = ..., visual: Incomplete | None = ...) -> None: ...
    @property
    def area(self): ...
    def contains(self, pixcoord): ...
    def to_sky(self, wcs): ...
    @property
    def bounding_box(self): ...
    def to_mask(self, mode: str = ..., subpixels: int = ...) -> None: ...
    def as_artist(self, origin=..., **kwargs): ...
    def rotate(self, center, angle): ...

class LineSkyRegion(SkyRegion):
    start: Incomplete
    end: Incomplete
    meta: Incomplete
    visual: Incomplete
    def __init__(self, start, end, meta: Incomplete | None = ..., visual: Incomplete | None = ...) -> None: ...
    def contains(self, skycoord, wcs): ...
    def to_pixel(self, wcs): ...
