from ..core.core import PixelRegion, SkyRegion
from _typeshed import Incomplete

class PolygonPixelRegion(PixelRegion):
    vertices: Incomplete
    meta: Incomplete
    visual: Incomplete
    origin: Incomplete
    def __init__(self, vertices, meta: Incomplete | None = ..., visual: Incomplete | None = ..., origin=...) -> None: ...
    @property
    def area(self): ...
    def contains(self, pixcoord): ...
    def to_sky(self, wcs): ...
    @property
    def bounding_box(self): ...
    def to_mask(self, mode: str = ..., subpixels: int = ...): ...
    def as_artist(self, origin=..., **kwargs): ...
    def rotate(self, center, angle): ...

class RegularPolygonPixelRegion(PolygonPixelRegion):
    center: Incomplete
    nvertices: Incomplete
    radius: Incomplete
    angle: Incomplete
    meta: Incomplete
    visual: Incomplete
    side_length: Incomplete
    inradius: Incomplete
    perimeter: Incomplete
    interior_angle: Incomplete
    exterior_angle: Incomplete
    def __init__(self, center, nvertices, radius, angle=..., meta: Incomplete | None = ..., visual: Incomplete | None = ...) -> None: ...
    def rotate(self, center, angle): ...
    def to_polygon(self): ...

class PolygonSkyRegion(SkyRegion):
    vertices: Incomplete
    meta: Incomplete
    visual: Incomplete
    def __init__(self, vertices, meta: Incomplete | None = ..., visual: Incomplete | None = ...) -> None: ...
    def to_pixel(self, wcs): ...
