"""
This type stub file was generated by pyright.
"""

import sys
from .base import Base
from .cds import CDS
from .console import Console
from .fits import Fits
from .generic import Generic, Unscaled
from .latex import Latex, LatexInline
from .ogip import OGIP
from .unicode_format import Unicode
from .vounit import VOUnit

"""
A collection of different unit formats.
"""
core = ...
__all__ = ['Base', 'Generic', 'CDS', 'Console', 'Fits', 'Latex', 'LatexInline', 'OGIP', 'Unicode', 'Unscaled', 'VOUnit', 'get_format']
def get_format(format=...): # -> Type[Generic] | Type[Base]:
    """
    Get a formatter by name.

    Parameters
    ----------
    format : str or `astropy.units.format.Base` instance or subclass
        The name of the format, or the format instance or subclass
        itself.

    Returns
    -------
    format : `astropy.units.format.Base` instance
        The requested formatter.
    """
    ...

