"""
This type stub file was generated by pyright.
"""

from . import console

"""
Handles the "Unicode" unit format.
"""
class Unicode(console.Console):
    """
    Output-only format to display pretty formatting at the console
    using Unicode characters.

    For example::

      >>> import astropy.units as u
      >>> print(u.bar.decompose().to_string('unicode'))
              kg
      100000 ────
             m s²
    """
    _times = ...
    _line = ...
    @classmethod
    def format_exponential_notation(cls, val): # -> str:
        ...
    


