"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from typing import Union

"""
For querying site information
"""

@lru_cache(maxsize=10)
def get_site(siteid: Union[int, str]) -> dict:
    """
    Get site information (defined per each instrument).
    Args:
        siteid: Optional[int, str] site id number.

    Returns: json of site (instrument) parameters.

    """
    ...

@lru_cache(maxsize=1)
def get_all_sites() -> dict:
    """
    Get info for all sites registered in FLOWS
    Returns: json of site (instrument) parameters.

    """
    ...
