from typing import Any

class DTYPE_BOOL(int):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __and__(self, other) -> Any: ...
    def __or__(self, other) -> Any: ...
    def __rand__(self, other) -> Any: ...
    def __ror__(self, other) -> Any: ...
    def __rxor__(self, other) -> Any: ...
    def __xor__(self, other) -> Any: ...

def points_in_polygon(*args, **kwargs) -> Any: ...
