# Creates a plain Github release, without attaching assets or source code.
name: Publish Release 
on:
  push:
    tags:
      - 'v*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: tag
      id: tag
      run: |
        TAG=${GITHUB_REF#refs/*/}
        VERSION=${TAG#v/*}
        echo "version-${VERSION}" >> $GITHUB_OUTPUT
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: "FlowsTools ${{ steps.tag.output.version }}: latest tagged release"
