# This workflow will upload a Python Package using Flit when a release is created

name: Deploy Python Package to PyPi with Flit 

on:
  release:
    types: [published]
    
  # Allows manual triggering from actions tab.  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build flit
      shell: bash
    - name: Build package
      run: flit build
    - name: deploy to PyPi with flit
      run: flit publish
      shell: bash
      env:
        FLIT_USERNAME: '__token__'
        FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        FLIT_INDEX_URL: 'https://upload.pypi.org/legacy/'
